# Generated by Django 5.0.6 on 2024-06-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('year_of_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('place_of_birth', models.CharField(max_length=255)),
                ('technical_skills', models.TextField()),
                ('soft_skills', models.TextField()),
                ('education', models.TextField()),
                ('languages', models.TextField()),
                ('certificates', models.TextField()),
                ('download_resume', models.FileField(upload_to='resumes/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pages.project')),
            ],
        ),
    ]
