# Generated by Django 5.0.6 on 2024-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0005_remove_post_author_remove_comment_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default=0, upload_to='skils/'),
            preserve_default=False,
        ),
    ]
