# Generated by Django 5.0.6 on 2024-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0006_remove_skill_level_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='skills/'),
        ),
    ]
