# Generated by Django 5.0.6 on 2024-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0007_alter_skill_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkilProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='skil',
            field=models.ManyToManyField(to='app_pages.skilproject'),
        ),
    ]
