# Generated by Django 5.0.6 on 2024-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0008_skilproject_remove_project_skills_project_skil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skil',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SkilProject',
        ),
    ]
